### ISSUE TITLE
Cannot load preset blocks/copper_ore in 1.19.3

### ISSUE THREAD

**Issue by awalian** [misode/misode.github.io#412] opened 2023-08-16 12:19 UTC
## Crash report
 * Page url: `https://misode.github.io/loot-table/?version=1.19.3`
 * Generator ID: `loot_table`
 * Current version: `1.19.3`
 * Latest version: `1.20.1`

### Generator JSON
<details>
<pre>
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone"
        }
      ]
    }
  ],
  "type": "minecraft:block"
}
</pre>
</details>

**Comment by misode** [comment] 2023-10-03 10:02
Most likely also duplicate of #360

**Closed by misode** 2023-10-03 10:02 UTC
