### ISSUE TITLE
Cannot load preset overworld in 1.21

### ISSUE THREAD

**Issue by hdjsgjc** [misode/misode.github.io#629] opened 2024-11-14 08:59 UTC
## Crash report
 * Page url: `https://misode.github.io/dimension-type/?version=1.21`
 * Generator ID: `dimension_type`
 * Current version: `1.21`
 * Latest version: `24w45a`

**Comment by misode** [comment] 2024-11-14 14:58
Duplicate of #360

**Closed by misode** 2024-11-14 14:58 UTC
