### ISSUE TITLE
Cannot load preset nether in 1.20

### ISSUE THREAD

**Issue by Goldgom** [misode/misode.github.io#582] opened 2024-08-05 20:16 UTC
## Crash report
 * Page url: `https://misode.github.io/worldgen/noise-settings/?version=1.20`
 * Generator ID: `worldgen/noise_settings`
 * Current version: `1.20`
 * Latest version: `1.21`

**Comment by misode** [comment] 2024-08-14 16:42
Duplicate of #360

**Closed by misode** 2024-08-14 16:42 UTC
