### ISSUE TITLE
Structure Generator - Start Height ("Constant" Bug?)

### ISSUE THREAD

**Issue by Gregory-AM** [misode/misode.github.io#523] opened 2024-05-18 16:29 UTC
When starting a new structure from the [Structure Generator](https://misode.github.io/worldgen/structure/) the Start Height is Constant with Absolute to its side.

![Screenshot 2024-05-18 112640](https://github.com/misode/misode.github.io/assets/83489100/619c4ea7-46c3-4fdb-a2ef-66ba3141e46d)

Changing this to any other value, whether it is Constant+, Uniform, biased to bottom, etc. Then changing it back to Constant completely hides the absolute value on the side along with value input.

![Screenshot 2024-05-18 112716](https://github.com/misode/misode.github.io/assets/83489100/2968045d-8ab6-4a87-af95-4cf10ea4c91d)

**Comment by misode** [comment] 2024-05-18 16:38
Duplicate of #413

**Closed by misode** 2024-05-18 16:38 UTC
