### ISSUE TITLE
[Suggestion] Don't remove unsupported files when uploading datapacks

### ISSUE THREAD

**Issue by ShaneBeee** [misode/misode.github.io#553] opened 2024-06-28 19:57 UTC
I would like to suggest keeping unsupported files when uploading a data pack.

For example:
I have generated a DataPack using this website.
I have then plopped it into IntelliJ where I sometimes do some changes.
I recently created a function (`.mcfunction`) to be used in my custom enchantment.
Unfortunately when I uploaded back to your site, that file doesn't show up.
Big issue here is if I make some changes to my custom enchantments, when I download the pack, the function is now gone.

I think it would be handle to still store those (maybe/maybe not actually show them) so they can be re-downloaded properly later on.

Thank you for your consideration.

**Comment by misode** [comment] 2024-06-28 20:04
Duplicate of #319

**Closed by misode** 2024-06-28 20:04 UTC
