### ISSUE TITLE
Worldgen visualizer sometimes cannot load vanilla noises

### ISSUE THREAD

**Issue by Oranamous** [misode/misode.github.io#264] opened 2022-07-18 18:59 UTC
In the worldgen visualizers, the preview often just shows solid gray. I've found that this is because the input is referencing noise (or density functions) from a different source. If there is a way to work around it on my end I'm all ears, but I haven't found one yet. I can imagine the difficulty in supporting the vanilla files but I imagine it's not too difficult since there's already a button that allows you to view and edit the individual noises already. I hope you have a great day, thanks Misode for making this already great tool!

**Comment by misode** [comment] 2022-07-19 07:03
It should already be able to load vanilla noises. Can you show what your JSON looks like?

**Comment by Danjhop4** [comment] 2022-07-23 19:28
{
  "type": "minecraft:overworld",
  "generator": {
    "type": "minecraft:noise",
    "settings": "minecraft:overworld",
    "biome_source": {
      "type": "minecraft:multi_noise",
      "biomes": [
        {
          "biome": "minecraft:plains",
          "parameters": {
            "temperature": 0,
            "humidity": 1,
            "continentalness": 2,
            "erosion": -2,
            "weirdness": 1,
            "depth": 0,
            "offset": 0
          }
        },
        {
          "biome": "minecraft:basalt_deltas",
          "parameters": {
            "temperature": 2,
            "humidity": -2,
            "continentalness": 1,
            "erosion": 1,
            "weirdness": -0.5,
            "depth": 0,
            "offset": 0
          }
        }
      ]
    }
  }
}

**Comment by Oranamous** [comment] 2022-07-23 20:18
Sorry for slow response, it happens when I load any density function or noise settings presets that reference another file in 1.19, I think it worked in 1.18 but I haven't checked since 1.19 dropped

**Comment by Danjhop4** [comment] 2022-07-24 10:30
Works in 1.18.2 unless you add  a biome

**Comment by Danjhop4** [comment] 2022-07-24 15:30
It’s for iOS 15.5

**Comment by misode** [comment] 2023-10-03 10:12
I think this might be caused by #360

**Comment by misode** [comment] 2024-10-04 03:06
Duplicate of #360

**Closed by misode** 2024-10-04 03:06 UTC
Labels: bug
