### ISSUE TITLE
Suspicious gravel/sand not able to have a set loot table.

### ISSUE THREAD

**Issue by Archerman123** [misode/misode.github.io#594] opened 2024-09-06 22:00 UTC
When adding a Component of the block_entity_data variety, you cannot pick any archeology-related ID. Not only that, it does not allow you to add the "loot table" value, which the game does accept and allows you to have a suspicious sand item in your inventory that can be placed to get an item.

Here is an example of what the game can process but not the generator:

"entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:suspicious_gravel",
          "functions": [
            {
              "function": "minecraft:set_components",
              "components": {
                "minecraft:block_entity_data": {
                  "id": "minecraft:suspicious_gravel",
                  "LootTable": "minecraft:archaeology/trail_ruins_rare"
                }
              }
            }
          ]
        }
      ]

**Comment by misode** [comment] 2024-09-11 11:30
The first issue is that the block ID is called `brushable_block`. The second issue where fields like `LootTable` are not able to be set, is a duplicate of #507

**Closed by misode** 2024-09-11 11:30 UTC
Labels: duplicate
