### ISSUE TITLE
Components in Recipe Generator isn't able to add "variant".

### ISSUE THREAD

**Issue by dragon3025** [misode/misode.github.io#570] opened 2024-07-19 04:58 UTC
For example this would craft a painting item that places down the water painting:
```
{
	"type": "minecraft:crafting_shapeless",
	"category": "misc",
	"ingredients": [
		{
			"item": "minecraft:painting"
		}
	],
	"result": {
		"id": "minecraft:painting",
		"components": {
			"minecraft:entity_data": {
				"id": "minecraft:painting",
				"variant": "minecraft:water"
			}
		}
	}
}
```

**Comment by misode** [comment] 2024-07-19 21:09
Duplicate of #507

**Closed by misode** 2024-07-19 21:09 UTC
