### ISSUE TITLE
[DF Generator] Various enhancement ideas

### ISSUE THREAD

**Issue by HB-Stratos** [misode/misode.github.io#460] opened 2024-02-01 02:36 UTC
I didn't want to create an issue for each random idea I had that I thought might be beneficial for the editor
- **Allow direct folder editing.**
Websites can access live folders on the hard disk. Jacobso's DF visualizer is capable of doing this. This could streamline the editing process as one could also locally copy/paste files, do quick edits, etc. and have them immediately show up on the website without cumbersome downloading zip, extracting, changing, repacking and reuploading while specifying a new name and the workspace. Before this change can be implemented the file overwriting bugs I reported earlier really need to be fixed though. I can't trust the editor as is.
- **Allow for seamless inserting of nodes with only one input field (or all nodes)**
Nodes like max, min, square, etc. all have a singular input field. So having a button that allows one to insert them anywhere in the call chain would make editing node chains a whole lot easier. Right now I have to select the right section in the json making sure to get the right number of closing brackets, cut the selection, add the new node, set its input to inline, then paste the cut selection again. This could be massively streamlined.
Additionally, it could also be possible to generalize this for multi input nodes where, when they get inserted, the previous values get pushed into either the first or second field. I would like to see a user setting here, but could live with always in first field.
- **Allow for seamless removal of nodes with only one input field**
Same reasoning as the previous suggestion. Nodes with only one input can be removed with no ambiguity, Not having to do this manually would again streamline editing.
- **Allow nodes and node groups to be dragged around**
e.g. if one has a node group, clicking and dragging on one node would grab it and its child nodes to be dragged to and placed in another input field. Holding shift while doing so could allow for seamless duplication too. 
- **Functions with input parameters**
Yes, those do not exist in DFs usually. Which is a massive pain. Having a way to specify an input parameter to a function and having the website 'compile' multiple DFs to fake the behavior of supporting multiple input parameters would be very nice. I had to copy-paste and change one value so many times for my worley implementation in DF. I do realize though that this is rather niche and ambiguous to implement.
- **Splines automatically select spline type**
Because who would want a spline of type none? More of a minor bug report really.
- **Being able to set a set seed, which persists between noise and df editor**
It would be very helpful if it was possible to specify an explicit seed if one has created a mc world with a seed in which something went wrong, and one wants to diagnose it in the editor. This is currently not possible. Switching between the noise and df editor should also not generate a new random seed, it just adds to user confusion and makes debugging harder.
- **Spline function fitting**
The DF functions lack a few crucial things, like e.g. sin(x) or 1/x. This can usually be worked around by using splines. I suggest a tool that allows the user to specify min and max value as well as acceptable accuracy, and it generates a spline that fits as closely as possible to an entered function. 
- **Add a warning if numbers bigger than what a datapack accepts to load are entered**
If a const is set to a value bigger than what MC accepts, a warning should show up to notify the player that their datapack won't actually load.

That's all I got for now. I'd appreciate it massively if some of these ideas could be implemented. And even if not, already a massive thank you for creating this awesome tool, without which I likely would have never gotten into mc world gen.

**Comment by misode** [comment] 2024-10-04 03:25
> Allow direct folder editing.

Good suggestion, together with #253 this is planned

> Allow for seamless inserting of nodes with only one input field (or all nodes)

Not sure if I will ever get around to this. Maybe I implement a generic drag-drop and/or copy-paste functionality, but that's far into the future.

> Allow for seamless removal of nodes with only one input field

Same as above

> Allow nodes and node groups to be dragged around

Also see above

> Functions with input parameters

Out of scope

> Splines automatically select spline type

This may not have been the case when you made this issue, but splines can now select any density function as coordinate, so it doesn't make much sense to pick a single default

> Being able to set a set seed, which persists between noise and df editor

Duplicate of #514 

> Spline function fitting

Out of scope

> Add a warning if numbers bigger than what a datapack accepts to load are entered

This could easily be changed in the schema. I guess DF values need to be withing -1 000 000 and 1 000 000?

**Comment by misode** [comment] 2024-11-21 04:28
I'm going to close this because it's hard to keep track of all the suggestions in a single issue. Please create a new issue per single suggestion that you'd like to see, taking into account my previous message.

**Closed by misode** 2024-11-21 04:28 UTC
Labels: enhancement
