### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DeroPlayz** [misode/misode.github.io#575] opened 2024-07-24 17:50 UTC
Would it be possible to add a function generator to the site? Nothing fancy, just a text editor where you can paste in functions. I love this site, but when my datapacks have functions, it's harder to make them through this site because I have to add the function folder to the zip file. Thanks a million regardless, and sorry if this is an annoying request!

**Comment by misode** [comment] 2024-08-14 16:43
Duplicate of #337

**Closed by misode** 2024-08-14 16:43 UTC
