### ISSUE TITLE
Cannot load preset acacia_fence in 1.19.3

### ISSUE THREAD

**Issue by ThatJadenXgamer** [misode/misode.github.io#315] opened 2022-12-30 12:30 UTC
## Crash report
 * Page url: `https://misode.github.io/recipe/?version=1.19.3`
 * Generator ID: `recipe`
 * Current version: `1.19.3`
 * Latest version: `1.19.3`

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:crafting_shaped",
  "pattern": [],
  "key": {},
  "result": {
    "item": "minecraft:stone"
  }
}
</pre>
</details>

**Comment by misode** [comment] 2022-12-30 12:55
@ThatJadenXgamer Could you try again? If that doesn't work could you verify that you can open this link, and it isn't blocked in your country? https://raw.githubusercontent.com/misode/mcmeta/data/data/minecraft/recipes/acacia_fence.json

**Comment by ThatJadenXgamer** [comment] 2023-01-01 16:20
it seems to be blocked in my country for whatever reason, it works fine with a VPN though, why is that?

**Comment by misode** [comment] 2023-01-03 22:03
Duplicate of #239

**Closed by misode** 2023-01-03 22:03 UTC
