### ISSUE TITLE
Error: Something went wrong creating the customized pack: Error occurred while fetching all dimension_type presets: Unexpected token '<', "<?xml vers"... is not valid JSON

### ISSUE THREAD

**Issue by nathgit** [misode/misode.github.io#415] opened 2023-09-05 04:32 UTC
## Crash report
 * Page url: `https://misode.github.io/customized/?tab=ores`
 * Current version: `1.20`
 * Latest version: `1.20.1`

### Stack trace
```
Error: Something went wrong creating the customized pack: Error occurred while fetching all dimension_type presets: Unexpected token '<', "
<?xml vers"... is not valid JSON
<?xml vers"... is not valid JSON
    at Oa (src/app/services/DataFetcher.ts:133:8)
    at async Promise.all (index 1)
    at async (src/app/components/customized/CustomizedGenerator.ts:27:40)
    at async (src/app/pages/Customized.tsx:60:16)
```

### Customized settings
<details>
<pre>
{}
</pre>
</details>

**Comment by misode** [comment] 2023-10-03 09:59
Most likely a duplicate of #360

**Closed by misode** 2023-10-03 09:59 UTC
