### ISSUE TITLE
Feature Request: Adding custom/modded items to the loot table generator

### ISSUE THREAD

**Issue by mezz8118** [misode/misode.github.io#476] opened 2024-02-27 11:29 UTC
I'd really appreciate the ability to import a list of modded items to the items list in loot tables, ideally in bulk via a single  text file or copy/paste rather than having to add each individually.
The generator being able to read the same format craft tweaker dumps item ids as would be a huge bonus. You could just have a single custom/modded/unknown item texture with the manually inputted name appear in the chest previews.

This is the craft tweaker dump format fyi:
<item:ad_astra:black_flag>
<item:ad_astra:blue_flag>
<item:ad_astra:brown_flag>

If this is too big a feature, even just being able to manually type in item ID's that don't match the preset options but still show up in the copyable code would be great. 

This would be  great help in creating modded loot tables as right now I have to create a template with placeholders in the generator, copy it to a separate document; then swap out all the placeholders for modded items. Which isn't the end of the world, but does take quite some time a lead to a few mistakes.

Thanks for taking the time to consider this!

**Comment by misode** [comment] 2024-10-04 02:48
Duplicate of #427

**Closed by misode** 2024-10-04 02:48 UTC
Labels: enhancement
