### ISSUE TITLE
Cannot load preset archaeology in 1.20.2

### ISSUE THREAD

**Issue by Resourcessa** [misode/misode.github.io#488] opened 2024-03-12 11:09 UTC
## Crash report
 * Page url: `https://misode.github.io/loot-table/?version=1.20.2`
 * Generator ID: `loot_table`
 * Current version: `1.20.2`
 * Latest version: `24w10a`

### Generator JSON
<details>
<pre>
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone"
        }
      ]
    }
  ],
  "type": "minecraft:empty"
}
</pre>
</details>

**Comment by misode** [comment] 2024-03-12 17:28
Duplicate of #360. If you have additional information (browser, country, VPN, whether github might be blocked, etc) please leave that in the linked issue.

**Closed by misode** 2024-03-12 17:28 UTC
