### ISSUE TITLE
Cannot load preset beacon in 1.21

### ISSUE THREAD

**Issue by BarbTurnip437** [misode/misode.github.io#588] opened 2024-08-17 13:25 UTC
## Crash report
 * Page url: `https://misode.github.io/recipe/?version=1.21`
 * Generator ID: `recipe`
 * Current version: `1.21`
 * Latest version: `1.21.1`

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "tag": "minecraft:acacia_logs"
    }
  ],
  "result": {
    "id": "minecraft:acacia_planks",
    "count": 4
  },
  "category": "building",
  "group": "planks"
}
</pre>
</details>

**Comment by misode** [comment] 2024-08-17 13:31
Duplicate of #360

**Closed by misode** 2024-08-17 13:31 UTC
