### ISSUE TITLE
Error rendering the tree: Cannot read properties of undefined (reading 'enabled')

### ISSUE THREAD

**Issue by JAVAHTML1** [misode/misode.github.io#375] opened 2023-05-20 03:21 UTC
## Crash report
 * Page url: `https://villagerconfig.vercel.app/villagerconfig/`
 * Generator ID: `villagerconfig`
 * Current version: `1.19.3`
 * Latest version: ``

### Generator JSON
<{
  "tiers": [
    {
      "total_exp_required": 4,
      "groups": [
        {
          "num_to_select": 10,
          "trades": [
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 3
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:white_shulker_box"
              },
              "trader_experience": 0,
              "max_uses": 2
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 3
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:green_shulker_box"
              },
              "trader_experience": 0
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 3
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:orange_shulker_box"
              },
              "trader_experience": 0
            }
          ]
        }
      ]
    },
    {
      "total_exp_required": 0,
      "groups": [
        {
          "num_to_select": 100,
          "trades": [
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald"
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:polished_andesite_slab"
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:diamond"
              },
              "trader_experience": 0
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:string",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 1,
                    "add": false
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:emerald"
              },
              "price_multiplier": 0,
              "trader_experience": 10,
              "max_uses": 1e+22,
              "reward_experience": true
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:diamond",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 1,
                    "add": false
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:spruce_log",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 64,
                    "add": false
                  }
                ]
              },
              "price_multiplier": 0.05,
              "trader_experience": 1,
              "max_uses": 10,
              "reward_experience": true
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 32,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.8
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 4,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.01
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 16,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.19
                      }
                    ]
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:book"
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:enchanted_book",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 1
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 2
                  },
                  {
                    "function": "minecraft:set_enchantments",
                    "enchantments": {
                      "minecraft:protection": 10,
                      "minecraft:fire_protection": 10,
                      "minecraft:projectile_protection": 10,
                      "minecraft:blast_protection": 10,
                      "minecraft:respiration": 6,
                      "minecraft:aqua_affinity": 2,
                      "minecraft:mending": 2,
                      "minecraft:unbreaking": 12,
                      "fabricenchantments:tank": 5,
                      "minecraft:thorns": 6
                    }
                  }
                ]
              },
              "price_multiplier": 0.2,
              "trader_experience": 10,
              "max_uses": 1,
              "reward_experience": false
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 32,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.8
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 4,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.01
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 16,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.19
                      }
                    ]
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:book"
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:enchanted_book",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 2
                  },
                  {
                    "function": "minecraft:set_enchantments",
                    "enchantments": {
                      "minecraft:protection": 10,
                      "minecraft:blast_protection": 10,
                      "minecraft:fire_protection": 10,
                      "minecraft:projectile_protection": 10,
                      "minecraft:unbreaking": 12,
                      "fabricenchantments:tank": 5,
                      "minecraft:mending": 2,
                      "minecraft:thorns": 6
                    }
                  }
                ]
              },
              "price_multiplier": 0.2,
              "trader_experience": 10,
              "max_uses": 1,
              "reward_experience": false
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 32,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.8
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 16,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.19
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 4,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.01
                      }
                    ]
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:book"
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:enchanted_book",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 2
                  },
                  {
                    "function": "minecraft:set_enchantments",
                    "enchantments": {
                      "minecraft:unbreaking": 12,
                      "minecraft:mending": 2,
                      "minecraft:swift_sneak": 6,
                      "minecraft:protection": 10,
                      "minecraft:fire_protection": 10,
                      "minecraft:blast_protection": 10,
                      "minecraft:projectile_protection": 10,
                      "fabricenchantments:tank": 5,
                      "minecraft:thorns": 6
                    }
                  }
                ]
              },
              "price_multiplier": 0,
              "trader_experience": 0,
              "max_uses": 2,
              "reward_experience": true
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 32,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.8
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 4,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.01
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 16,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.19
                      }
                    ]
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:book",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 1
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:enchanted_book",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 2
                  },
                  {
                    "function": "minecraft:set_enchantments",
                    "enchantments": {
                      "minecraft:feather_falling": 8,
                      "minecraft:soul_speed": 6,
                      "minecraft:depth_strider": 6,
                      "minecraft:frost_walker": 2,
                      "minecraft:mending": 2,
                      "minecraft:unbreaking": 12,
                      "minecraft:protection": 10,
                      "minecraft:projectile_protection": 10,
                      "minecraft:fire_protection": 10,
                      "minecraft:blast_protection": 10,
                      "fabricenchantments:tank": 5,
                      "minecraft:thorns": 6
                    }
                  }
                ]
              },
              "trader_experience": 0
            }
          ]
        }
      ]
    },
    {
      "total_exp_required": 2000,
      "groups": [
        {
          "num_to_select": 2,
          "trades": [
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 1,
                    "add": false
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:name_tag",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 64,
                    "add": false
                  }
                ]
              },
              "price_multiplier": 0.05,
              "trader_experience": 30,
              "max_uses": 10,
              "reward_experience": true
            }
          ]
        }
      ]
    },
    {
      "total_exp_required": 1,
      "groups": [
        {
          "num_to_select": 2,
          "trades": [
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:diamond",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 5
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 4
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:netherite_ingot",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 2,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.2
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 1,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.8
                      }
                    ]
                  }
                ]
              },
              "price_multiplier": 0.2,
              "trader_experience": 2000,
              "max_uses": 4,
              "reward_experience": false
            }
          ]
        }
      ]
    },
    {
      "total_exp_required": 100000,
      "groups": [
        {
          "num_to_select": 5,
          "trades": [
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 32,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.9
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 16,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.09
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 4,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.01
                      }
                    ]
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:book"
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:enchanted_book",
                "functions": [
                  {
                    "function": "minecraft:set_enchantments",
                    "enchantments": {
                      "minecraft:sharpness": 10,
                      "minecraft:sweeping": 6,
                      "minecraft:unbreaking": 12,
                      "minecraft:fire_aspect": 4,
                      "minecraft:bane_of_arthropods": 10,
                      "minecraft:smite": 10,
                      "minecraft:mending": 2,
                      "minecraft:knockback": 4,
                      "minecraft:looting": 6
                    }
                  }
                ]
              },
              "trader_experience": 0
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 64,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.9
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 32,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.09
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 16,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.01
                      }
                    ]
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:netherite_ingot",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 2
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:netherite_pickaxe",
                "functions": [
                  {
                    "function": "minecraft:set_enchantments",
                    "enchantments": {
                      "minecraft:unbreaking": 12,
                      "minecraft:mending": 2,
                      "minecraft:efficiency": 10,
                      "minecraft:fortune": 12
                    }
                  }
                ]
              },
              "price_multiplier": 0.2,
              "trader_experience": 0,
              "max_uses": 1,
              "reward_experience": true
            },
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:emerald",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 64,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.9
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 32,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.09
                      }
                    ]
                  },
                  {
                    "function": "minecraft:set_count",
                    "count": 16,
                    "conditions": [
                      {
                        "condition": "minecraft:random_chance",
                        "chance": 0.01
                      }
                    ]
                  }
                ]
              },
              "cost_b": {
                "type": "minecraft:item",
                "name": "minecraft:netherite_ingot",
                "functions": [
                  {
                    "function": "minecraft:set_count",
                    "count": 2
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:netherite_axe",
                "functions": [
                  {
                    "function": "minecraft:set_enchantments",
                    "enchantments": {
                      "minecraft:sharpness": 10,
                      "minecraft:unbreaking": 12,
                      "minecraft:mending": 2,
                      "minecraft:efficiency": 7,
                      "minecraft:smite": 10,
                      "minecraft:bane_of_arthropods": 10,
                      "fabricenchantments:double_swing": 2,
                      "fabricenchantments:consumer": 6,
                      "fabricenchantments:god_of_thunder": 2,
                      "fabricenchantments:experience": 4,
                      "fabricenchantments:ice_aspect": 4,
                      "fabricenchantments:poison_aspect": 4,
                      "fabricenchantments:paralysis": 4,
                      "fabricenchantments:pyromania": 4,
                      "fabricenchantments:replenish": 2,
                      "fabricenchantments:rise": 6
                    }
                  },
                  {
                    "function": "minecraft:set_name",
                  }
                ]
              },
              "trader_experience": 0
            }
          ]
        }
      ]
    }
  ]
}

**Comment by misode** [comment] 2023-05-25 10:06
This is an issue with the fork, which is not supported here. Duplicate of #358.

**Closed by misode** 2023-05-25 10:06 UTC
