### ISSUE TITLE
SyntaxError: Something went wrong rendering the generator: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by TruMiner** [misode/misode.github.io#601] opened 2024-09-14 16:07 UTC
## Crash report
 * Page url: `https://misode.github.io/loot-table/?version=1.21.2`
 * Generator ID: `loot_table`
 * Current version: `1.21.2`
 * Latest version: `24w37a`

### Stack trace
```
SyntaxError: Something went wrong rendering the generator: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    at parse (src/app/components/ItemTooltip.tsx:118:34)
    at map (src/app/components/ItemTooltip.tsx:117:18)
    at n8 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at Rh (../../node_modules/preact/dist/preact.module.js:1:5862)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at j (../../node_modules/preact/dist/preact.module.js:1:1493)
    at jc (../../node_modules/preact/dist/preact.module.js:1:1391)

```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:shearing",
  "pools": [
    {
      "rolls": 5,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone",
          "weight": 99,
          "functions": [
            {
              "function": "minecraft:set_components",
              "components": {
                "minecraft:custom_name": "{\"text\":\"[custom name]\",\"italic\":false,\"color\":\"green\"}",
                "minecraft:item_model": "[custom model location]",
                "minecraft:max_stack_size": 99,
                "minecraft:death_protection": {},
                "minecraft:lore": [
                  ""
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:red_mushroom",
          "weight": 1
        }
      ],
      "bonus_rolls": 0
    }
  ],
  "random_sequence": "minecraft:shearing/mooshroom/red"
}
</pre>
</details>

**Comment by misode** [comment] 2024-09-18 15:31
Duplicate of #599

**Closed by misode** 2024-09-18 15:31 UTC
