### ISSUE TITLE
[Suggestion] Allow for uploading of custom item icons

### ISSUE THREAD

**Issue by Nataly171** [misode/misode.github.io#452] opened 2024-01-03 18:01 UTC
The loot table preview is super convenient, but it's slightly less helpful when you start including modded items in the loot table. I think a reasonable solution would be to allow users to upload their own icons for items, even if it doesn't get saved.

**Comment by misode** [comment] 2024-10-04 03:18
Duplicate of #427

**Closed by misode** 2024-10-04 03:18 UTC
