### ISSUE TITLE
Cannot load preset blocks/copper_ore in 1.19.4

### ISSUE THREAD

**Issue by isZKahh** [misode/misode.github.io#469] opened 2024-02-18 06:28 UTC
## Crash report
 * Page url: `https://misode.github.io/loot-table/?version=1.19.4`
 * Generator ID: `loot_table`
 * Current version: `1.19.4`
 * Latest version: `24w03b`

### Generator JSON
<details>
<pre>
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone"
        }
      ]
    }
  ],
  "type": "minecraft:block"
}
</pre>
</details>

**Comment by misode** [comment] 2024-02-19 13:21
Duplicate of #360

**Closed by misode** 2024-02-19 13:21 UTC
