### ISSUE TITLE
VillagerConfig "Error rendering the tree: Cannot read properties of undefined (reading 'enabled')"

### ISSUE THREAD

**Issue by JAVAHTML1** [misode/misode.github.io#374] opened 2023-05-16 22:57 UTC
I was trying to name an item for villagers to trade, but I got this error: "Error rendering the tree: Cannot read properties of undefined (reading 'enabled')
    at Object.enabled (../../node_modules/@mcschema/core/lib/nodes/Reference.js:18:35)
    at enabled (src/app/schema/transformOutput.ts:55:32)
    at Array.filter (<anonymous>)
    at filter (src/app/schema/transformOutput.ts:55:4)
    at Object.hook (../../node_modules/@mcschema/core/lib/nodes/ObjectNode.js:109:83)
    at hook (../../node_modules/@mcschema/core/lib/nodes/Reference.js:42:51)
    at hook (src/app/schema/transformOutput.ts:24:12)
    at Array.map (<anonymous>)
    at map (src/app/schema/transformOutput.ts:23:20)
    at Object.hook (../../node_modules/@mcschema/core/lib/nodes/ListNode.js:59:81)"
Anybody else having this problem/know how to fix it?

**Comment by misode** [comment] 2023-05-25 10:06
This is an issue with the fork, which is not supported here. Duplicate of #358.

**Closed by misode** 2023-05-25 10:06 UTC
