### ISSUE TITLE
Error: Cannot get version "1.19": caches is not defined

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [misode/misode.github.io#280] opened 2022-08-18 12:44 UTC
```
Error: Cannot get version "1.19": caches is not defined
    at (http://command.aely.vip/src/app/services/Schemas.ts:39:15) (Schemas.ts:69:10)
```

**Comment by misode** [comment] 2022-08-18 16:06
Duplicate of #275

**Closed by misode** 2022-08-18 16:06 UTC
Labels: duplicate

**Comment by Thexiaoyuqaq** [comment] 2022-08-18 17:06
I use the demo site https://misode.github.io/generators/
It can be used normally, but I can't build it myself
I switched to Edge and the same problem
