### ISSUE TITLE
"entity_data" component in loot tables only has "id" field

### ISSUE THREAD

**Issue by arvitus** [misode/misode.github.io#562] opened 2024-07-10 18:38 UTC
When using the `entity_data` component in the `Set components` function of a loot table, it only has an `id` field and removes any additional data. While you should be able to add fields like `Tags` or `CustomName` (normal entity data), this won't work. You can write it into the json preview but as soon as you click out of it, any additional data will be deleted and only the `id` field is kept. Ideally you should be able to specify any entity data using the gui, but for now it would already be sufficient if additional data wouldn't be deleted. Otherwise this component is pretty useless right now.

possibly related to #507

**Comment by misode** [comment] 2024-08-14 16:52
I'm going to mark this as a duplicate of #507

**Closed by misode** 2024-08-14 16:52 UTC
