### ISSUE TITLE
Cannot load loot table presets in 1.20

### ISSUE THREAD

**Issue by VidTDM** [misode/misode.github.io#448] opened 2023-12-10 09:33 UTC
Every time I click on a preset I get this
![image](https://github.com/misode/misode.github.io/assets/77015935/038b2633-c9e1-4f85-8dbe-434cd7b46168)

**Comment by misode** [comment] 2023-12-10 13:19
Duplicate of #360. If you have more information about when this happens, please add it to that ticket. It might be a regional issue, or a temporary downtime.

**Closed by misode** 2023-12-10 13:19 UTC
