### ISSUE TITLE
TypeError: Something went wrong rendering the generator: o.id.equals is not a function

### ISSUE THREAD

**Issue by oinpig** [misode/misode.github.io#306] opened 2022-11-23 06:15 UTC
```
TypeError: Something went wrong rendering the generator: o.id.equals is not a function
    at equals (src/app/previews/LootTable.ts:78:15)
    at result (src/app/previews/LootTable.ts:44:14)
    at generateLootTable (src/app/components/previews/LootTablePreview.tsx:27:16)
    at g1 (../../node_modules/preact/hooks/dist/hooks.module.js:1:2451)
    at Array.forEach (<anonymous>)
    at e6 (../../node_modules/preact/hooks/dist/hooks.module.js:1:1395)
```

**Comment by misode** [comment] 2022-11-23 07:07
To help reproduce this issue, can you share what the loot table JSON was when you got this error?

**Comment by misode** [comment] 2022-11-24 04:33
Going to resolve this as a duplicate of #307 because that contains more info

**Closed by misode** 2022-11-24 04:33 UTC
