### ISSUE TITLE
Entity data only takes id not other nbt

### ISSUE THREAD

**Issue by L-Lawlite** [misode/misode.github.io#492] opened 2024-03-23 03:34 UTC
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.20.5`
 * Latest version: `24w12a`

### Stack trace
```
SyntaxError: Error importing: Unexpected end of JSON input
    at yi (../../node_modules/comment-json/src/parse.js:94:16)
    at unexpected_end (../../node_modules/comment-json/src/parse.js:120:4)
    at type (../../node_modules/comment-json/src/parse.js:128:16)
    at is (../../node_modules/comment-json/src/parse.js:246:10)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:417:15)
    at parse (src/app/services/Source.ts:24:23)
    at async (src/app/services/Source.ts:43:8)
    at async (src/app/components/generator/SourcePanel.tsx:71:17)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:empty",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:armor_stand",
          "functions": [
            {
              "function": "minecraft:set_components",
              "components": {
                "minecraft:custom_name": "'{\"text\":\"MineBot\",\"italic\":false}'",
                "minecraft:custom_model_data": 1,
                "minecraft:entity_data": {
                  "id": "minecraft:armor_stand",
                  "ShowId": 1
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment] 2024-09-12 14:19
I'm going to forward resolve this as a duplicate of #507

**Closed by misode** 2024-09-12 14:19 UTC
Labels: bug, ✨ schemas
