### ISSUE TITLE
Cannot load preset the_nether in 1.20.2

### ISSUE THREAD

**Issue by gebixiaoxiaopa** [misode/misode.github.io#440] opened 2023-11-22 08:47 UTC
## Crash report
 * Page url: `https://misode.github.io/dimension-type/?version=1.20.2`
 * Generator ID: `dimension_type`
 * Current version: `1.20.2`
 * Latest version: `23w40a`

### Generator JSON
<details>
<pre>
{
  "ultrawarm": false,
  "natural": true,
  "piglin_safe": false,
  "respawn_anchor_works": false,
  "bed_works": true,
  "has_raids": true,
  "has_skylight": true,
  "has_ceiling": true,
  "coordinate_scale": 1,
  "ambient_light": 0,
  "logical_height": 256,
  "infiniburn": "#minecraft:infiniburn_overworld",
  "min_y": 0,
  "height": 256,
  "monster_spawn_light_level": 0,
  "monster_spawn_block_light_limit": 0
}
</pre>
</details>

**Comment by misode** [comment] 2023-11-22 14:57
Duplicate of #360

**Closed by misode** 2023-11-22 14:57 UTC
