### ISSUE TITLE
Site Becoming Unresponsive

### ISSUE THREAD

**Issue by Correlander** [misode/misode.github.io#422] opened 2023-09-30 22:27 UTC
1. Open noise_settings generator
2. Change the int under Noise Options -> Size Vertical to 0
3. Click elsewhere for the change to be "finalized"

Version of generator is for MC 1.19

**Comment by misode** [comment] 2023-10-01 17:46
Duplicate of #418

**Closed by misode** 2023-10-01 17:46 UTC
