### ISSUE TITLE
Cannot load preset overworld in 1.20.2

### ISSUE THREAD

**Issue by gebixiaoxiaopa** [misode/misode.github.io#446] opened 2023-12-04 08:25 UTC
## Crash report
 * Page url: `https://misode.github.io/worldgen/noise-settings/?version=1.20.2`
 * Generator ID: `worldgen/noise_settings`
 * Current version: `1.20.2`
 * Latest version: `1.20.3-rc1`

### Generator JSON
<details>
<pre>
{
  "sea_level": 63,
  "disable_mob_generation": false,
  "aquifers_enabled": false,
  "ore_veins_enabled": true,
  "legacy_random_source": false,
  "default_block": {
    "Name": "minecraft:stone"
  },
  "default_fluid": {
    "Name": "minecraft:water",
    "Properties": {
      "level": "0"
    }
  },
  "noise": {
    "min_y": -64,
    "height": 384,
    "size_horizontal": 1,
    "size_vertical": 2
  },
  "noise_router": {
    "barrier": 0,
    "fluid_level_floodedness": 0,
    "fluid_level_spread": 0,
    "lava": 0,
    "temperature": 0,
    "vegetation": 0,
    "continents": 0,
    "erosion": 0,
    "depth": 0,
    "ridges": 0,
    "initial_density_without_jaggedness": 0,
    "final_density": {
      "type": "minecraft:interpolated",
      "argument": "minecraft:overworld/base_3d_noise"
    },
    "vein_toggle": 0,
    "vein_ridged": 0,
    "vein_gap": 0
  },
  "spawn_target": [],
  "surface_rule": {
    "type": "minecraft:sequence",
    "sequence": []
  }
}
</pre>
</details>

**Comment by misode** [comment] 2023-12-04 15:16
Duplicate of #360. If you have more information about where and when this happened, please leave a message there.

**Closed by misode** 2023-12-04 15:16 UTC
