### ISSUE TITLE
TypeError: Something went wrong rendering the generator: Something went wrong rendering the generator: can't convert undefined to BigInt

### ISSUE THREAD

**Issue by firenh** [misode/misode.github.io#216] opened 2022-03-26 22:59 UTC
```
TypeError: Something went wrong rendering the generator: Something went wrong rendering the generator: can't convert undefined to BigInt
    at jn (src/app/previews/NoiseSettings.ts:236:32)
    at constructor (../../node_modules/preact/dist/preact.module.js:1:8049)
    at render (../../node_modules/preact/dist/preact.module.js:1:5824)
    at n2 (../../node_modules/preact/dist/preact.module.js:1:2156)
    at m (../../node_modules/preact/dist/preact.module.js:1:6057)
    at n2 (../../node_modules/preact/dist/preact.module.js:1:2156)
    at m (../../node_modules/preact/dist/preact.module.js:1:7265)
    at i2 (../../node_modules/preact/dist/preact.module.js:1:6241)
    at n2 (../../node_modules/preact/dist/preact.module.js:1:2156)
    at m (../../node_modules/preact/dist/preact.module.js:1:6057)
    at I (../../node_modules/preact/dist/preact.module.js:1:1518)
    at some (../../node_modules/preact/dist/preact.module.js:1:1416)

```

**Comment by misode** [comment] 2022-03-26 23:14
Duplicate of #215

**Closed by misode** 2022-03-26 23:14 UTC
Labels: duplicate
