### ISSUE TITLE
Cannot load preset in 1.20.2

### ISSUE THREAD

**Issue by Resourcessa** [misode/misode.github.io#484] opened 2024-03-07 14:45 UTC
## Crash report
 * Page url: `https://misode.github.io/recipe/?version=1.20.2`
 * Generator ID: `recipe`
 * Current version: `1.20.2`
 * Latest version: `24w10a`

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:blasting",
  "ingredient": {
    "item": "minecraft:raw_iron"
  },
  "result": "minecraft:iron_ingot",
  "category": "misc",
  "cookingtime": 100,
  "experience": 0.7,
  "group": "iron_ingot"
}
</pre>
</details>

**Comment by misode** [comment] 2024-03-07 14:53
Duplicate of #360

**Closed by misode** 2024-03-07 14:53 UTC
