### ISSUE TITLE
Cannot load preset blocks/copper_ore in 1.19.3

### ISSUE THREAD

**Issue by hi54123** [misode/misode.github.io#397] opened 2023-07-03 04:25 UTC
* Page url: `https://misode.github.io/loot-table/?version=1.19.3`
*  * Generator ID: `loot_table`
* Current version: `1.19.3`
* Latest version: `1.20.1`

**Comment by misode** [comment] 2023-10-03 10:06
Duplicate of #360

**Closed by misode** 2023-10-03 10:06 UTC
