### ISSUE TITLE
[Affects misode.github.io/dev] Nothing is considered valid in the Biome option for advancements and loot tables

### ISSUE THREAD

**Issue by ManosSef** [misode/misode.github.io#105] opened 2020-07-23 06:30 UTC
!(https://user-images.githubusercontent.com/65536780/88257742-1e789a80-ccc7-11ea-9b25-27daa29a39e1.PNG)

**Comment by misode** [comment] 2020-08-10 18:46
This was caused by a change in the mcdata repository. Fixed in https://github.com/misode/dev/commit/a175976c48f7b6b4a30cbfb0e25f7047f8e3105c.

**Closed by misode** 2020-08-10 18:46 UTC
