### ISSUE TITLE
Recipe Generator Missing Options

### ISSUE THREAD

**Issue by UnrealPuggy** [misode/misode.github.io#524] opened 2024-05-18 23:34 UTC
When using the Recipe Generator, I was using the 1.20.6 version of it. I was making a recipe for a armor stand and was trying to add a custom item for the armor stand. However, the entity_data tag does not allow me to add other options besides the id so I had to manually add stuff in.

**Comment by misode** [comment] 2024-05-19 00:04
Duplicate of #507

**Closed by misode** 2024-05-19 00:04 UTC
