### ISSUE TITLE
TypeError: Something went wrong rendering the generator: Something went wrong rendering the generator: Something went wrong rendering the generator: Something went wrong rendering the generator: E.split(...).at is not a function

### ISSUE THREAD

**Issue by Cwalpor** [misode/misode.github.io#557] opened 2024-07-05 03:58 UTC
## Crash report
 * Page url: `https://misode.github.io/advancement/`
 * Generator ID: `advancement`
 * Current version: `1.21`
 * Latest version: `1.21`

### Stack trace
```
TypeError: Something went wrong rendering the generator: Something went wrong rendering the generator: Something went wrong rendering the generator: Something went wrong rendering the generator: E.split(...).at is not a function
    at at (src/app/components/generator/ProjectPanel.tsx:131:27)
    at V4 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at du (../../node_modules/preact/dist/preact.module.js:1:5862)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at j (../../node_modules/preact/dist/preact.module.js:1:1493)
    at q0 (../../node_modules/preact/dist/preact.module.js:1:1391)

```

### Generator JSON
<details>
<pre>
{
  "criteria": {
    "sprinting": {
      "trigger": "minecraft:tick",
      "conditions": {
        "player": [
          {
            "condition": "minecraft:entity_properties",
            "entity": "this",
            "predicate": {
              "type": "more_exhaustion:swim"
            }
          },
          {
            "condition": "minecraft:entity_properties",
            "entity": "this",
            "predicate": {
              "type": "more_exhaustion:sprint"
            }
          }
        ]
      }
    }
  },
  "rewards": {
    "function": "more_exhaustion:player/sprint"
  }
}
</pre>
</details>

I am not able to clear the code in the window, perpetuating the error code. How do I reset the website back to when it didn't save whatever I wrote in it? like when i first opened the website?

**Comment by misode** [comment] 2024-07-11 03:10
Duplicate of #536

**Closed by misode** 2024-07-11 03:10 UTC

**Comment by misode** [comment] 2024-07-11 03:12
> I am not able to clear the code in the window, perpetuating the error code. How do I reset the website back to when it didn't save whatever I wrote in it? like when i first opened the website?

You can always press Ctrl+Z to undo changes you make. An alternative is reloading the page and using the "Restore last backup" option
